// This is the whole app layout file. It is used to wrap all the pages.
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css"; // --- IGNORE for textbook 1.2.4---
import "bootstrap/dist/css/bootstrap.min.css";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify"; // for popup error alerts 
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Scales page to view on local machine */}
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* Toast notification container */}
        <ToastContainer 
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        
      </body>
    </html>
  );
}
